### ISSUE TITLE
Nice work! Could please tell me where to get the mamba_new package?

### ISSUE THREAD

**Issue by 924973292** [YuqiZhang-Buaa/Mamba2MIL#1]

**Comment by YuqiZhang-Buaa** [comment]
I am honoured that you are interested in our work. mamba_new is the nomenclature we use to distinguish the previous version of mamba from [here](https://github.com/state-spaces/mamba). You can also contact me at the email address in the paper if you have any questions.

**Comment by 924973292** [comment]
Thanks for your reply!
